### ISSUE TITLE
Not receiving any notifications

### ISSUE THREAD

**Issue by siamkreative** [gedex/wp-slack-contact-form-7#1]
Hey there,

First of all thanks for the great plugin :)

Here is my setup:
- WordPress 4.0
- Slack Version 0.5.0
- Slack Contact Form 7 Version 0.1.0
- Contact Form 7 Version 3.9.3
- Mailgun Version 1.3

I don't receive any notifications for CF7 but I do receive notifications for new post / page. I haven't had the chance to receive a notification for EDD yet.

Any idea why?

Cheers

**Comment by gedex** [comment]
Hi @SiamKreative,

Not sure yet why it doesn't send the notification, I'll check it later. Thanks for the report.

**Comment by greggh** [comment]
I am not receiving the notifications either. The Slack plugin itself sends the "Test sending payload!" just fine. And I get all of the other notifications, just not the contact form 7 one.

I am also using the Contact Form 7 DB plugin, and the entries are getting added there so I know the hooks are working.

**Comment by ghost** [comment]
Seems like a solution still has not been found for this, I'm having the same issues as @greggh

**Comment by greggh** [comment]
@lonejasmine I "fixed" it on my end by horribly breaking the code I am sure. But I got it working for me.
Here is the copy of my slack-contact-form-7.php: http://pastebin.com/q1f8iK0k
I removed some of the conditional stuff, and got it working fine.

**Comment by jmardesign** [comment]
thanks for the fix @greggh - It's working like a charm, but I was wondering if you knew how to change it from sending the slack message after submission to send mail. I have multistep forms setup and I am getting overwhelmed by notifications after each step of the form. Ideally, I'd like to receive the notifications after the form is finished and the email sent. Any help would be amazing!

**Comment by greggh** [comment]
I haven't had to deal with any multistep stuff, our forms are all single step contact forms. Sorry. There might be some other trigger you can deal with, right now the code works with "wpcf7_mail_sent". It's strange that it notifies you after every step though, I wouldn't think "mail_sent" was called every step of a multi-step form.

**Comment by gedex** [comment]
This should be fixed on 0.2.0. Published already to wp.org. Thanks for the report and input everyone!
